services:
  - type: web
    name: Back_Twitter_Laravel
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: mysql-base1cine.alwaysdata.net
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: base1cine_twicopy
      - key: DB_USERNAME
        value: base1cine_admin
      - key: DB_PASSWORD
        value: contrasena_1234